Add `/api/stub/project_ids` endpoint
BuidlGuidl/onchain-impact-dashboard pull request #34
Opened 2024-07-02 01:10 UTC by swellander

## Description
Adds an endpoint to return just a list of all project ids for us to use internally to generate all the project detail static pages

2024-07-02 01:16 UTC, Franpastoragusti commented on packages/nextjs/app/project/[id]/page.tsx
> +  const data: Project[] = await response.json();
this is a string[] no a project[]

2024-07-02 01:44 UTC, swellander commented on packages/nextjs/app/project/[id]/page.tsx
> +  const data: Project[] = await response.json();
good catch!

2024-07-03 21:31 UTC, swellander commented on packages/firebase/seed.sample.json
Updated the seed sample file `projects` with agora projects with OSO id mappings

2024-07-05 12:42 UTC, escottalexander commented
I am going to dig in to why the build is still failing. This looks good so nice work!

2024-07-05 15:31 UTC, escottalexander requested changes
One thing with two parts that made me have issues. Almost there. Thanks.

2024-07-05 15:31 UTC, escottalexander commented on packages/nextjs/app/project/[id]/page.tsx
This file won't display for me due to lines 43-56 where `[...data?.github, ...data?.packages]`. If the project doesn't have `github` or `packages` properties then the spread operator is trying to act upon undefined causing this error:
`Error: (intermediate value) is not iterable`.

We should check for the existence of `github` and `packages` before using the spread operator.

2024-07-05 15:32 UTC, escottalexander commented
> I am going to dig in to why the build is still failing. This looks good so nice work!

I might need to reseed the production data for the build to succeed. I will give that a try when you commit the fixes I discussed in my review.

2024-07-05 15:40 UTC, escottalexander requested changes

2024-07-05 15:40 UTC, escottalexander commented on packages/nextjs/pages/api/projects/detail/[id].ts
> +    const projectDetailDto = convertProjectToDto(projectDetail);
The request from the project page needs more than the dto version. It needs the whole Project.

2024-07-05 19:56 UTC, escottalexander commented
@swellander https://github.com/BuidlGuidl/onchain-impact-dashboard/pull/46 has the seed data changes for projects covered. If it gets merged in before this then you can remove your changes to `seed.sample.json` and just get the changes contained in that PR.

2024-07-09 18:17 UTC, closed without merging

2024-07-09 18:17 UTC, escottalexander commented
Closing this since all the relevant changes were absorbed by #46. Thanks for your help with this @swellander.