Project movement model
BuidlGuidl/onchain-impact-dashboard pull request #69
Opened 2024-07-16 17:35 UTC by swellander

## Description
Creates a new model `ProjectMovement` to replace the `ProjectMetricSummary` model. The new model bundles together the 7/30/90 day % movement summaries for every active metric, as well as includes some info about the project (everything needed to populate the [Leaderboard table](https://www.figma.com/design/SuY5W6zRajPNOrmeCSTvAq/Onchain-Impact-Dashboard?node-id=337-2366&t=ionD6ZYvc3TZyMJT-0))

2024-07-16 17:37 UTC, swellander commented on packages/nextjs/pages/api/projectMetricSummary/index.ts
I'm replacing this with a `/api/projectMovement/index.ts` route as part of the [leaderboard](https://github.com/BuidlGuidl/onchain-impact-dashboard/issues/47) ticket

2024-07-17 18:43 UTC, escottalexander requested changes
One small comment.

2024-07-17 18:43 UTC, escottalexander commented on packages/nextjs/services/mongodb/models/projectMovement.ts
> +  (mongoose.models.ProjectMovement as IProjectMovementModel) ||
This should be 
```
(mongoose.models.temp_ProjectMovement as IProjectMovementModel) || ...
                 ^^^^^
```

2024-07-17 21:42 UTC, swellander commented on packages/nextjs/services/mongodb/models/projectMovement.ts
> +  (mongoose.models.ProjectMovement as IProjectMovementModel) ||
good catch

2024-07-17 22:02 UTC, escottalexander approved these changes

2024-07-17 22:02 UTC, merged