Real metric names
BuidlGuidl/onchain-impact-dashboard pull request #99
Opened 2024-07-27 20:03 UTC by swellander

## Description
Updates our metric names and OSO data to be in sync with the [current version of OSO's API](https://models.opensource.observer/#!/model/model.opensource_observer.rf4_impact_metrics_by_project#columns)

## Additional Information
- Removes our references to the `mapping` object, that we no longer need because OSO includes an `application_id` field that is also the project's ID on Agora.
- Changes dummy data values to be more random than progressive, trying to mimic the time-bound metric values [that we will be showing](https://github.com/BuidlGuidl/onchain-impact-dashboard/issues/93)

2024-07-27 20:07 UTC, swellander commented on packages/nextjs/app/types/OSO.ts
> +  application_id: string;
This is the same as the project's Agora ID

2024-07-27 20:07 UTC, swellander commented on packages/nextjs/pages/api/etl/impact_metric_weights.json
> +        "impact_index": 1.0
Added `impact_index` here artificially to satisfy our TS compiler

2024-07-27 20:08 UTC, swellander commented on packages/nextjs/pages/api/etl/index.ts
> +import weightData from "./impact_metric_weights.json";
Pulling in the actual weights, now that our metric names line up

2024-07-28 11:22 UTC, escottalexander requested changes
This is great. Appreciate you doing this. One issue is that we will still need the mapping. The source for the metric names was a static data set that had the mapping already added to each project but in the future we will pull the data from a different source and it is unlikely that this data will include the mapping data. Feel free to reach out for more clarity.

2024-07-29 19:32 UTC, escottalexander approved these changes
LGTM!

2024-07-29 19:33 UTC, merged